<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="ClienteEliminar.aspx.cs" Inherits="Proyecto_Final.ClienteEliminar" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <br />
        <br />
        Seleccione el nombre del cliente que desea eliminar:
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="NOMBRE" DataValueField="NOMBRE" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" SelectCommand="SELECT DISTINCT NOMBRE FROM CC.CLIENTE"></asp:SqlDataSource>
    
    </div>
        <p>
            &nbsp;</p>
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True">
        </asp:GridView>
        <asp:SqlDataSource ID="SqlDataSource2" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" DeleteCommand="DELETE FROM CC.CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE" SelectCommand="SP_SELECT_CLIENTE" SelectCommandType="StoredProcedure">
            <DeleteParameters>
                <asp:Parameter Name="ID_CLIENTE" />
            </DeleteParameters>
            <SelectParameters>
                <asp:Parameter Name="NOMBRE" Type="String" />
            </SelectParameters>
        </asp:SqlDataSource>
    </form>
</body>
</html>
