<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EliminarCompra.aspx.cs" Inherits="Proyecto_Final.WebForm2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <br />
        Seleccione el nombre de usuario con el que quiere eliminar la compra:&nbsp;
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="nombreusuario" DataValueField="nombreusuario" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" SelectCommand="select nombreusuario from cc.cliente "></asp:SqlDataSource>
    
    </div>
        <asp:GridView ID="GridView1" onrowdeleting="GridView1_RowDeleting" runat="server" AutoGenerateDeleteButton="True">
        </asp:GridView>
&nbsp;</form>

</body>
</html>
