<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EliminarPlanta.aspx.cs" Inherits="Proyecto_Final.EliminarPlanta" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
 
        <br />
        Eliminar Planta:
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="NOMBRE" DataValueField="NOMBRE" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" SelectCommand="SELECT DISTINCT NOMBRE FROM CC.PLANTA"></asp:SqlDataSource>
 
    </div>
        <asp:GridView ID="GridView1" runat="server" onrowdeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True">
        </asp:GridView>
    </form>
</body>
</html>
