<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="EliminarCuenta.aspx.cs" Inherits="Proyecto_Final.EliminarCuenta" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        &nbsp;Seleccione el nombre de usuario al que pertenece la cuenta que desea eliminar:
        <asp:DropDownList ID="DropDownList1" runat="server" AutoPostBack="True" DataSourceID="SqlDataSource1" DataTextField="nombreusuario" DataValueField="nombreusuario" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" SelectCommand="Select distinct nombreusuario from cc.cuenta"></asp:SqlDataSource>
    
    </div>
        <asp:GridView ID="GridView1" runat="server" onrowdeleting="GridView1_RowDeleting" AutoGenerateDeleteButton="True">
        </asp:GridView>
        <asp:TextBox ID="p" runat="server"></asp:TextBox>
    </form>
</body>
</html>
