<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="prueba.aspx.cs" Inherits="Proyecto_Final.prueba" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <title></title>
</head>
<body>
    <form id="form1" runat="server">
    <div>
    
        <br />
        <br />
        Seleccione el nombre del cliente que desea eliminar<br />
        <asp:DropDownList ID="DropDownList1" runat="server" DataSourceID="SqlDataSource3" DataTextField="nombre" DataValueField="nombre" AutoPostBack="True" OnSelectedIndexChanged="DropDownList1_SelectedIndexChanged">
        </asp:DropDownList>
        <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" SelectCommand="select * from cc.cliente where nombre = @nombre" DeleteCommand="delete from cc.cliente where id_clente = @id_cliente">
            <DeleteParameters>
                <asp:Parameter Name="id_cliente" />
            </DeleteParameters>
            <SelectParameters>
                   <asp:ControlParameter Name="RoleID" ControlID="DropDownList1" 
          PropertyName="SelectedValue" />
            </SelectParameters>
        </asp:SqlDataSource>
        <asp:SqlDataSource ID="SqlDataSource3" runat="server" ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>" SelectCommand="select  distinct nombre from cc.cliente"></asp:SqlDataSource>
        <br />
        <br />
        <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" Height="66px" Width="134px">
        </asp:GridView>
        <br />
        <asp:SqlDataSource ID="SqlDataSource2"
             runat="server" 
            ConnectionString="<%$ ConnectionStrings:SQLAzureConnection %>"
             DeleteCommand="DELETE FROM CC.CLIENTE WHERE ID_CLIENTE = @ID_CLIENTE" 
            SelectCommand="CC.SP_SELECT_CLIENTE" SelectCommandType="StoredProcedure">
            <DeleteParameters>
                <asp:Parameter Name="ID_CLIENTE" />
            </DeleteParameters>
            <SelectParameters>
                <asp:Parameter Name="nombre" />
            </SelectParameters>
        </asp:SqlDataSource>
    
    </div>
    </form>
</body>
</html>
